import { useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Check, ChevronDown, Heart, Menu, Search, ShieldCheck, SlidersHorizontal, Sparkles, X, Zap } from 'lucide-react'
import './App.css'

const vehicles = [
  { id: 1, name: 'Audi RS e-tron GT', type: 'Eléctrico', year: 2024, price: 118900, mileage: '1.200 km', image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85', featured: true },
  { id: 2, name: 'BMW M4 Competition', type: 'Gasolina', year: 2023, price: 86900, mileage: '18.400 km', image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85' },
  { id: 3, name: 'Porsche 911 Carrera', type: 'Gasolina', year: 2022, price: 104500, mileage: '9.800 km', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85' },
  { id: 4, name: 'Mercedes-Benz GLC 300', type: 'Híbrido', year: 2024, price: 72900, mileage: '4.600 km', image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85' },
  { id: 5, name: 'Range Rover Sport', type: 'Diésel', year: 2023, price: 95800, mileage: '21.300 km', image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85' },
  { id: 6, name: 'Volvo XC60 Recharge', type: 'Híbrido', year: 2024, price: 64900, mileage: '3.100 km', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85' },
]

const formatPrice = (price) => new Intl.NumberFormat('es-ES').format(price)

function App() {
  const [query, setQuery] = useState('')
  const [type, setType] = useState('Todos')
  const [sort, setSort] = useState('Destacados')
  const [favorites, setFavorites] = useState([])
  const [selectedVehicle, setSelectedVehicle] = useState(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const filteredVehicles = useMemo(() => {
    const matching = vehicles.filter((vehicle) => (type === 'Todos' || vehicle.type === type) && vehicle.name.toLowerCase().includes(query.toLowerCase()))
    if (sort === 'Precio menor') return [...matching].sort((a, b) => a.price - b.price)
    if (sort === 'Precio mayor') return [...matching].sort((a, b) => b.price - a.price)
    return matching
  }, [query, sort, type])
  const toggleFavorite = (vehicleId) => setFavorites((current) => current.includes(vehicleId) ? current.filter((id) => id !== vehicleId) : [...current, vehicleId])

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#inicio" aria-label="NOVA MOTORS inicio"><span className="brand-mark">N</span><span>NOVA <b>MOTORS</b></span></a><nav className={menuOpen ? 'main-nav is-open' : 'main-nav'}><a href="#vehiculos" onClick={() => setMenuOpen(false)}>Vehículos</a><a href="#servicios" onClick={() => setMenuOpen(false)}>Servicios</a><a href="#nosotros" onClick={() => setMenuOpen(false)}>Nosotros</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a></nav><div className="header-actions"><button className="favorites-link" type="button"><Heart size={17} fill="currentColor" /> {favorites.length}</button><a className="header-cta" href="#contacto">Vender mi coche <ArrowRight size={16} /></a><button className="menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <main id="inicio">
      <section className="hero-section"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14} /> SELECCIÓN PRIVADA · 2024</p><h1>Conduce lo<br /><em>extraordinario.</em></h1><p className="hero-text">Una colección curada de vehículos excepcionales. Compra con confianza, conduce con intención.</p><div className="hero-buttons"><a className="primary-button" href="#vehiculos">Explorar colección <ArrowRight size={18} /></a><a className="text-button" href="#contacto">Habla con un experto <ArrowRight size={16} /></a></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=1600&q=90" alt="Porsche deportivo en carretera" /></div><div className="hero-note"><span>01</span><span>Modelos que<br />dejan huella.</span></div></div><div className="hero-stats"><div><strong>120<span>+</span></strong><small>vehículos seleccionados</small></div><div><strong>15</strong><small>marcas de lujo</small></div><div><strong>4.9<span>★</span></strong><small>valoración de clientes</small></div></div></section>
      <section className="inventory-section" id="vehiculos"><div className="section-heading"><div><p className="eyebrow">LA COLECCIÓN</p><h2>Encuentra tu próximo<br /><em>capítulo.</em></h2></div><p className="section-intro">Cada vehículo de NOVA MOTORS ha sido inspeccionado, certificado y preparado para superar tus expectativas.</p></div><div className="filter-bar"><div className="search-box"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar marca o modelo" /></div><div className="filter-select"><SlidersHorizontal size={17} /><select value={type} onChange={(event) => setType(event.target.value)}><option>Todos</option><option>Eléctrico</option><option>Gasolina</option><option>Híbrido</option><option>Diésel</option></select><ChevronDown size={16} /></div><div className="sort-select"><span>Ordenar por</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option>Destacados</option><option>Precio menor</option><option>Precio mayor</option></select><ChevronDown size={16} /></div></div><div className="results-line"><span>{filteredVehicles.length} vehículos disponibles</span><span className="line" /><span>Actualizado hoy</span></div><div className="vehicle-grid">{filteredVehicles.map((vehicle) => <article className="vehicle-card" key={vehicle.id}><div className="vehicle-image"><img src={vehicle.image} alt={vehicle.name} /><button className={favorites.includes(vehicle.id) ? 'favorite-button active' : 'favorite-button'} onClick={() => toggleFavorite(vehicle.id)} aria-label="Guardar vehículo"><Heart size={18} fill={favorites.includes(vehicle.id) ? 'currentColor' : 'none'} /></button>{vehicle.featured && <span className="featured-label">Destacado</span>}</div><div className="vehicle-content"><div className="vehicle-meta"><span>{vehicle.year}</span><span>{vehicle.type}</span><span>{vehicle.mileage}</span></div><h3>{vehicle.name}</h3><div className="vehicle-bottom"><strong>{formatPrice(vehicle.price)} €</strong><button className="details-button" onClick={() => setSelectedVehicle(vehicle)}>Ver detalles <ArrowRight size={15} /></button></div></div></article>)}</div>{filteredVehicles.length === 0 && <div className="empty-state">No hemos encontrado vehículos con esos criterios.</div>}<div className="view-all"><button type="button" onClick={() => { setQuery(''); setType('Todos') }}>Ver toda la colección <ArrowRight size={17} /></button></div></section>
      <section className="promise-section" id="servicios"><div><p className="eyebrow">LA DIFERENCIA NOVA</p><h2>Más que un coche.<br /><em>Una certeza.</em></h2></div><div className="promise-grid"><div><ShieldCheck /><h3>Compra con confianza</h3><p>Inspección de 150 puntos y garantía incluida en cada vehículo.</p></div><div><Zap /><h3>Entrega sin esperas</h3><p>Recibe tu nuevo coche donde quieras en tan solo 72 horas.</p></div><div><CalendarDays /><h3>Atención personal</h3><p>Un experto a tu lado desde la primera consulta hasta la entrega.</p></div></div></section>
      <section className="contact-section" id="contacto"><div><p className="eyebrow">¿TIENES UN VEHÍCULO?</p><h2>Tu coche también<br /><em>merece NOVA.</em></h2></div><div><p>Valoramos tu vehículo de forma transparente y encontramos a su próximo dueño.</p><a className="primary-button light" href="mailto:hola@novamotors.es">Quiero vender mi coche <ArrowRight size={18} /></a></div></section>
    </main><footer id="nosotros"><span>© 2024 NOVA MOTORS</span><span>Madrid · Barcelona · Valencia</span><span>Instagram &nbsp; LinkedIn</span></footer>
    {selectedVehicle && <div className="modal-backdrop" onClick={() => setSelectedVehicle(null)}><div className="vehicle-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedVehicle(null)} aria-label="Cerrar"><X size={20} /></button><img src={selectedVehicle.image} alt={selectedVehicle.name} /><div><p className="eyebrow">{selectedVehicle.year} · {selectedVehicle.type}</p><h2>{selectedVehicle.name}</h2><p className="modal-price">{formatPrice(selectedVehicle.price)} €</p><p className="modal-description">Un vehículo excepcional, revisado por nuestros especialistas y listo para acompañarte en tu próxima aventura.</p><p className="modal-check"><Check size={16} /> Garantía NOVA incluida</p><a className="primary-button" href="mailto:hola@novamotors.es">Solicitar información <ArrowRight size={17} /></a></div></div></div>}
  </div>
}

export default App
